### ISSUE TITLE
Instructions in README don't work, "no exported member 'EmailOptions'."

### ISSUE THREAD

**Issue by xird** [wisekaa03/nestjs-mailgun#1]
Hi
I'm trying to take this module in use by following the examples in the README, but I'm getting this error:

src/components/notification/notification.service.ts:3:10 - error TS2305: Module '"nestjs-mailgun"' has no exported member 'EmailOptions'.

I checked the module's source code, and there's no mention of "EmailOptions". Any advice?

**Comment by wisekaa03** [comment]
It's a REAME problem. Ok now.
